---
title: Theme
author: KW
date: '2017-10-04'
slug: theme
categories: []
tags: []
---

## startujemy z 'gołym' wykresem
```{r message=FALSE, warning=FALSE, fig.align='center'}
library(ggplot2)
x = rnorm(n = 1000, mean = 50)
plot = ggplot() + geom_histogram(aes(x), bins = 50)
plot
```

### Jak dodać tytuł do wykresu w ggplot?
```{r fig.align='center'}
plot +
  ggtitle(label = 'Tytuł wykresu', subtitle = 'Podtytuł wykresu')
```

### Jak dodać/zmienić tytuł osi x i y?
```{r fig.align='center'}
plot +
  xlab('Tytuł osi x') +
  ylab('Tytuł osi y')
```

#### To samo można zrobić przy zastosowaniiu jednej funkcji:
```{r fig.align='center'}
plot +
  labs(title= 'Tytuł wykresu', 
       subtitle = 'Podtytuł wykresu', 
       x = 'Tytuł osi x',
       y = 'Tytuł osi y')
```
### Jak dodać podpis (caption) pod wykresem?
```{r fig.align='center'}
plot +
  labs(caption = 'Tutaj podpis wykresu, np. źródło url')
```


## Jak modyfikować czcionkę w wykresach? Wielkość, font, wyrównanie? A może chcesz się ich całkowicie pozbyć?
### (kliknij tutaj)