---
title: geom_point
author: KW
date: '2017-10-03'
slug: geom-point
categories: []
tags: []
output: html_document
---

Wykres punktowy jest jeszcze prostszy od wykresu słupkowego.

```{r}
library(ggplot2)
library(datasets)
```
Początek jest zawsze ten sam: ggplot()
Funkcja która rysuje kropki na wykresie to geom_point()

```{r fig.align='center'}
ggplot(data = women,
       aes(x = height, y = weight)) +
         geom_point()
```

Dodatkowymi argumentami geom_point mogą być: *kształt, kolor, wielkość*.

## Kolor

```{r fig.align='center'}
ggplot(data = women,
       aes(x = height, y = weight)) +
         geom_point(color = '#0099CC')
```

## Rodzaje punktorów i wielkość

```{r echo=FALSE, fig.align='center', fig.width=10}
df = data.frame(x = rep(1:5,5), y = rep(1:5,each = 5 ), shape = factor(1:25))
a = ggplot(data = df,
       aes(x = x, y = y,group=shape,shape=shape)) +
         geom_point(size= 3) +
  scale_shape_manual(values = 1:25) +
  geom_text(aes(x = x, y = y, label = shape), hjust = -1) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = 'none') +
  xlim(0.5, 5.5) +
  scale_y_reverse()
df2 = data.frame(y = rep(1:3, each = 3), x = rep(1:3, 3), size = factor(1:9))
b = ggplot(data = df2,
       aes(x = x, y = y, size = size, group = size)) +
         geom_point() +
  scale_size_manual(values = 1:9) +
  geom_text(aes(x = x, y = y, label = size), hjust = -1, size = 6) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = 'none') +
  scale_y_reverse()+
xlim(0.5, 3.5)
gridExtra::grid.arrange(a, b, ncol = 2)
```


```{r fig.align='center'}
ggplot(data = women,
       aes(x = height, y = weight)) +
  geom_point(shape = 17, color = '#0099CC', size = 4)
```